server:
  port: 50000
spring:
  datasource:
    url: jdbc:mysql:///springbootdata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  mapper-locations: mapper.demospringsecurity/*.xml
logging:
  level:
    com:
      example:
        demospringsecurity:
          mapper: debug